const dotenv = require('dotenv');
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const User = require('./models/User');
const Category = require('./models/Category');
const Product = require('./models/Product');

dotenv.config();

// comparePrice from a selling price + "discount up to X%" (as given in the client's catalog)
const cp = (price, pct) => Math.round((price / (1 - pct / 100)) * 100) / 100;

const categoriesData = [
  { name: 'For Her', slug: 'for-her', description: 'Elegant fragrances crafted for her' },
  { name: 'For Him', slug: 'for-him', description: 'Bold fragrances crafted for him' },
  { name: 'Unisex', slug: 'unisex', description: 'Fragrances for everyone' },
];

// Products no longer sold — deleted from the DB on seed if present
const legacySlugs = ['velvet-rose', 'midnight-oud', 'citrus-breeze', 'golden-amber'];

const productsData = [
  {
    name: 'The Story Sport',
    slug: 'the-story-sport',
    description: 'The Story Sport by Le Bonheur Perfumes is a refreshing Eau de Parfum created for those who embrace movement, ambition, and new beginnings. Blending vibrant citrus notes with aromatic florals and a warm woody base, this energetic fragrance delivers a clean and uplifting scent that is perfect for active days and warm-weather occasions.',
    shortDescription: 'Vibrant citrus with an aromatic floral-woody base',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img1.png', public_id: '' }],
    notes: { top: ['Grapefruit', 'Bergamot', 'Lemon'], middle: ['Fig', 'Jasmine', 'Pink Pepper'], base: ['Cedarwood', 'Benzoin', 'Amber'] },
    tags: ['le bonheur', 'citrus', 'woody', 'unisex'],
  },
  {
    name: 'Black Cavalier Surge',
    slug: 'black-cavalier-surge',
    description: "Black Cavalier Surge by Le Bonheur Perfumes is a bold Eau de Parfum crafted for those who embrace confidence and effortless style. Fresh citrus notes blend seamlessly with warm spices and rich woody accords, creating a sophisticated fragrance that balances vibrant energy with lasting depth for any occasion.",
    shortDescription: 'Fresh citrus with warm spice and woody depth',
    price: 75,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    images: [{ url: '/products/img2.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Orange', 'Ginger'], middle: ['Frankincense', 'Neroli', 'Cinnamon'], base: ['Dry Amber', 'Guaiac Wood', 'Black Tea'] },
    tags: ['le bonheur', 'spicy', 'woody', 'unisex'],
  },
  {
    name: "Reine D'Or Eliza",
    slug: 'reine-dor-eliza',
    description: "Reine D'Or Eliza by Le Bonheur Perfumes is a luxurious Eau de Parfum inspired by the quiet confidence and refined presence of royalty. Delicate jasmine blossoms intertwine with the creamy richness of tuberose, creating a graceful floral composition that embodies classic femininity, sophistication, and effortless elegance.",
    shortDescription: 'Delicate jasmine and creamy tuberose',
    price: 85,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img3.png', public_id: '' }],
    notes: { top: ['Jasmine'], middle: ['Tuberose'], base: ['Floral Accords'] },
    tags: ['le bonheur', 'floral', 'women'],
  },
  {
    name: 'Black Cavalier Seductive',
    slug: 'black-cavalier-seductive',
    description: 'Black Cavalier Seductive by Le Bonheur Perfumes is a luxurious Eau de Parfum crafted for those who appreciate confidence, elegance, and timeless charm. Fresh bergamot and soothing lavender create an inviting opening, while rich patchouli, warm amber, tobacco, and black vanilla unfold into a deeply sophisticated fragrance that leaves a lasting impression.',
    shortDescription: 'Bergamot and lavender over patchouli, amber and tobacco',
    price: 75,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img4.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Lavender'], middle: ['Patchouli', 'Amber'], base: ['Vanilla', 'Tobacco'] },
    tags: ['le bonheur', 'woody', 'unisex'],
  },
  {
    name: 'Qumra Perfume',
    slug: 'qumra-perfume',
    description: 'Experience the elegance and allure of Qumra Perfume by Le Bonheur, a sophisticated fragrance crafted for the modern woman. With its captivating blend of citrus, sweet caramel, and rich vanilla, this perfume offers a luxurious scent that lingers throughout the day.',
    shortDescription: 'Citrus, sweet caramel and rich vanilla',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img5.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Cinnamon'], middle: ['Caramel'], base: ['Vanilla', 'Amber'] },
    tags: ['le bonheur', 'gourmand', 'women'],
  },
  {
    name: 'Asturi Wood',
    slug: 'asturi-wood',
    description: 'Asturi Wood by Le Bonheur Perfumes is a luxurious Eau de Parfum inspired by the beauty of golden wood glowing beneath the sunset. A delicate floral opening unfolds into a rich gourmand heart before settling into the creamy warmth of sandalwood, creating a sophisticated fragrance that embodies elegance, comfort, and lasting refinement.',
    shortDescription: 'Floral opening into creamy sandalwood',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img6.png', public_id: '' }],
    notes: { top: ['Rose'], middle: ['Caramel'], base: ['Sandalwood'] },
    tags: ['le bonheur', 'woody', 'unisex'],
  },
  {
    name: 'Remember Me Blue',
    slug: 'remember-me-blue',
    description: 'Remember Me Blue by Le Bonheur Perfumes is a modern Eau de Parfum that reflects timeless elegance and understated confidence. Blending vibrant freshness with warm, sensual depth, this masculine fragrance is designed for the man who leaves a lasting impression without saying a word.',
    shortDescription: 'Vibrant freshness with warm, sensual depth',
    price: 55,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    isBestSeller: true,
    images: [{ url: '/products/img7.png', public_id: '' }],
    notes: { top: ['Maninka Fruit', 'Apple'], middle: ['Bran', 'Patchouli', 'Cedarwood'], base: ['Sandalwood', 'Amber', 'Vanilla', 'White Musk'] },
    tags: ['le bonheur', 'fresh', 'men'],
  },
  {
    name: 'Black Cavalier VI',
    slug: 'black-cavalier-vi',
    description: 'Black Cavalier VI Perfume by Le Bonheur Perfumes is a captivating fragrance that embodies sophistication and elegance. With a masterful blend of fresh and earthy notes, this scent is perfect for anyone who seeks a bold yet refined fragrance for any occasion.',
    shortDescription: 'Fresh and earthy, bold yet refined',
    price: 75,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img8.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Ginger'], middle: ['Violet'], base: ['Cedarwood', 'Sandalwood', 'Patchouli'] },
    tags: ['le bonheur', 'earthy', 'men'],
  },
  {
    name: 'Lara',
    slug: 'lara',
    description: 'Lara by Almas Perfumes is a captivating Eau de Parfum that exudes mystery, elegance, and allure. Designed for the confident and graceful woman, this luxurious scent blends the creamy sweetness of vanilla with soft jasmine, warm sandalwood, and juicy notes of apricot and peach — creating an irresistible classic that commands attention.',
    shortDescription: 'Creamy vanilla, jasmine, sandalwood, apricot and peach',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img9.png', public_id: '' }],
    notes: { top: [], middle: ['Vanilla', 'Jasmine', 'Sandalwood'], base: ['Apricot', 'Peach'] },
    tags: ['almas', 'floral', 'women'],
  },
  {
    name: 'Moira',
    slug: 'moira',
    description: 'Immerse yourself in the luxurious scent of Moira Perfume by Almas Perfumes, a distinctive French fragrance that exudes elegance and allure. With a blend of fruity and floral notes, this captivating perfume reflects your refined personality and adds a touch of sophistication to any occasion.',
    shortDescription: 'Fruity-floral French fragrance',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img10.png', public_id: '' }],
    notes: { top: ['Cherry', 'Lychee', 'Pear'], middle: ['Rose', 'Jasmine', 'Raspberry'], base: ['Vanilla', 'Patchouli', 'Amber'] },
    tags: ['almas', 'fruity', 'women'],
  },
  {
    name: 'Aura Bloom',
    slug: 'aura-bloom',
    description: 'Let your presence linger with Aura Bloom by Almas Perfumes, a French-style Eau de Parfum that tells your story with every note. Rich, elegant, and irresistibly feminine, this fragrance opens with a burst of sweet fruitiness, flows into a radiant floral-amber heart, and finishes with a warm, creamy base. Designed for women who embody sophistication and unforgettable grace.',
    shortDescription: 'Sweet fruitiness into a floral-amber heart',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img11.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Plum', 'Red Fruits'], middle: ['Amber', 'Jasmine'], base: ['Caramel Cream', 'Musk', 'Vanilla'] },
    tags: ['almas', 'fruity', 'women'],
  },
  {
    name: 'Wow Pistachio',
    slug: 'wow-pistachio',
    description: 'Elevate your scent game with Wow Pistachio by Almas Perfumes, a unisex Eau de Parfum that exudes luxury and warmth. This decadent fragrance blends creamy pistachio with sweet vanilla and soft woody notes, delivering a bold yet comforting aroma that lingers beautifully. Designed for fragrance lovers who seek uniqueness and elegance in every spray.',
    shortDescription: 'Creamy pistachio with sweet vanilla and soft wood',
    price: 85,
    comparePrice: 0,
    gender: 'Unisex',
    size: '200ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img12.png', public_id: '' }],
    notes: { top: ['Pistachio', 'Almond', 'Bergamot'], middle: ['Jasmine', 'Caramel', 'White Flowers'], base: ['Vanilla', 'Tonka Bean', 'Sandalwood'] },
    tags: ['almas', 'gourmand', 'unisex'],
  },
  {
    name: 'White Heart',
    slug: 'white-heart',
    description: 'Experience the brilliance and distinction of White Heart, a captivating fragrance by Almas Perfumes. This vibrant perfume blends citrus, fruity, and warm notes to create a refreshing and luxurious scent. Perfect for both personal and formal occasions, White Heart makes you feel lively and wonderful throughout the day.',
    shortDescription: 'Citrus, fruity and warm musk-amber notes',
    price: 55,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img13.png', public_id: '' }],
    notes: { top: ['Orange', 'Bergamot', 'Lemon'], middle: ['Fruits'], base: ['White Musk', 'Amber', 'Madagascar Vanilla'] },
    tags: ['almas', 'citrus', 'unisex'],
  },
  {
    name: 'Everyday Sweety',
    slug: 'everyday-sweety',
    description: 'Everyday Sweety Perfume by Almas Perfumes offers a captivating and luxurious fragrance designed for women who appreciate elegance and charm. This exquisite French perfume, with its unique blend of honey, bergamot, and cashmere, adds a touch of brilliance to your daily look, leaving a lasting impression with its long-lasting scent.',
    shortDescription: 'Honey, bergamot and cashmere',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img14.png', public_id: '' }],
    notes: { top: ['Honey', 'Bergamot', 'Orange'], middle: ['Cashmere', 'Apple', 'Caramel'], base: ['Musk', 'Vanilla', 'Patchouli'] },
    tags: ['almas', 'gourmand', 'women'],
  },
  {
    name: 'Club de Nuit Intense Man',
    slug: 'club-de-nuit-intense-man',
    description: 'Club de Nuit Intense Man by Armaf is a Woody Spicy fragrance for men, launched in 2015.',
    shortDescription: 'Woody spicy fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img15.png', public_id: '' }],
    notes: { top: ['Lemon', 'Pineapple', 'Bergamot', 'Black Currant', 'Apple'], middle: ['Birch', 'Jasmine', 'Rose'], base: ['Musk', 'Ambergris', 'Patchouli', 'Vanilla'] },
    tags: ['armaf', 'woody', 'spicy', 'men'],
  },
  {
    name: 'Club de Nuit Untold',
    slug: 'club-de-nuit-untold',
    description: 'Club de Nuit Untold by Armaf is a fragrance for women and men, launched in 2022.',
    shortDescription: 'Saffron and jasmine over amberwood and cedar',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img16.png', public_id: '' }],
    notes: { top: ['Saffron', 'Jasmine'], middle: ['Amberwood', 'Ambergris'], base: ['Fir Resin', 'Cedar'] },
    tags: ['armaf', 'unisex'],
  },
  {
    name: 'Club De Nuit Maleka',
    slug: 'club-de-nuit-maleka',
    description: 'Club De Nuit Maleka by Armaf is a Floral Fruity fragrance for women, launched in 2025. The nose behind this fragrance is Olivier Cresp.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img17.png', public_id: '' }],
    notes: { top: ['Lychee', 'Bergamot', 'Pink Pepper'], middle: ['Orris'], base: ['Praline', 'Sandalwood', 'Ambroxan'] },
    tags: ['armaf', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Musamam White Intense',
    slug: 'musamam-white-intense',
    description: 'Musamam White Intense by Lattafa Perfumes is an Oriental Floral fragrance for women and men, launched in 2023. The nose behind this fragrance is Gaël Montero.',
    shortDescription: 'Oriental floral fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img18.png', public_id: '' }],
    notes: { top: ['Spices', 'Bergamot', 'Orange'], middle: ['Coconut', 'Ylang Ylang', 'Ambroxan', 'Mahonial'], base: ['Sandalwood', 'Musk', 'Benzoin'] },
    tags: ['lattafa', 'oriental', 'floral', 'unisex'],
  },
  {
    name: 'Angham',
    slug: 'angham',
    description: 'Angham by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2024.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img19.png', public_id: '' }],
    notes: { top: ['Ginger', 'Mandarin', 'Pink Pepper'], middle: ['Lavender', 'Praline', 'Cacao', 'Jasmine'], base: ['Vanilla', 'Amber', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: "Bade'e Al Oud Sublime",
    slug: 'badee-al-oud-sublime',
    description: "Bade'e Al Oud Sublime by Lattafa Perfumes is a Woody Aromatic fragrance for women and men, launched in 2023.",
    shortDescription: 'Woody aromatic fragrance for women and men',
    price: 50,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img20.png', public_id: '' }],
    notes: { top: ['Apple', 'Litchi', 'Rose'], middle: ['Plum', 'Jasmine'], base: ['Moss', 'Vanilla', 'Patchouli'] },
    tags: ['lattafa', 'woody', 'unisex'],
  },
  {
    name: 'Cloud Candy',
    slug: 'cloud-candy',
    description: 'Cloud Candy by Khadlaj Perfumes is a fragrance for women and men, launched in 2025.',
    shortDescription: 'Sweet gourmand fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img21.png', public_id: '' }],
    notes: { top: [], middle: ['Marshmallow', 'Strawberry', 'Sugar', 'Whipped Cream', 'Vanilla', 'Raspberry', 'White Musk', 'Coconut', 'Tangerine', 'Ambroxan', 'Freesia'], base: [] },
    tags: ['khadlaj', 'gourmand', 'women'],
  },
  {
    name: 'Vintage Radio',
    slug: 'vintage-radio',
    description: 'Vintage Radio by Lattafa Perfumes is an Oriental Woody fragrance for women and men, launched in 2023.',
    shortDescription: 'Oriental woody fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img22.png', public_id: '' }],
    notes: { top: ['Lavender', 'Sage', 'Bergamot'], middle: ['Plum', 'Palo Santo', 'Black Pepper'], base: ['Sandalwood', 'Oud'] },
    tags: ['lattafa', 'oriental', 'woody', 'unisex'],
  },
  {
    name: 'Victoria',
    slug: 'victoria',
    description: 'Victoria by Lattafa Perfumes is a Floral Fruity Gourmand fragrance for women and men, launched in 2025.',
    shortDescription: 'Floral fruity gourmand fragrance',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img23.png', public_id: '' }],
    notes: { top: ['Lemon Meringue Pie'], middle: ['Neroli'], base: ['Vanilla'] },
    tags: ['lattafa', 'gourmand', 'unisex'],
  },
  {
    name: 'Fatima Pink',
    slug: 'fatima-pink',
    description: 'Fatima Pink by Zimaya is an Oriental Floral fragrance for women, launched in 2023.',
    shortDescription: 'Oriental floral fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img24.png', public_id: '' }],
    notes: { top: ['Rhubarb', 'Bergamot', 'Grapefruit', 'Nutmeg'], middle: ['Rose', 'Jasmine'], base: ['Musk', 'Vanilla', 'Vetiver', 'Ambergris'] },
    tags: ['zimaya', 'oriental', 'floral', 'women'],
  },
  {
    name: 'Opulent Dubai',
    slug: 'opulent-dubai',
    description: 'Opulent Dubai by Lattafa Perfumes is an Oriental Floral fragrance for women and men, launched in 2025.',
    shortDescription: 'Oriental floral fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img25.png', public_id: '' }],
    notes: { top: ['Mango', 'Grapefruit', 'Lemon', 'Ginger'], middle: ['Jasmine', 'Cedarwood', 'Violet'], base: ['Woodsy Notes', 'Ambergris', 'Oakmoss', 'Benzoin'] },
    tags: ['lattafa', 'oriental', 'unisex'],
  },
  {
    name: 'Atheeri',
    slug: 'atheeri',
    description: 'Atheeri by Lattafa Perfumes is an Oriental Floral fragrance for women, launched in 2025.',
    shortDescription: 'Oriental floral fragrance for women',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img26.png', public_id: '' }],
    notes: { top: ['Passion Flower', 'Dew Drop'], middle: ['Orchid', 'Jasmine'], base: ['Vanilla', 'Amberwood'] },
    tags: ['lattafa', 'oriental', 'floral', 'women'],
  },
  {
    name: 'Nebras',
    slug: 'nebras',
    description: 'Nebras by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2022.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img27.png', public_id: '' }],
    notes: { top: ['Red Berries', 'Mandarin Orange'], middle: ['Vanilla', 'Cacao', 'Rose'], base: ['Sugar', 'Tonka Bean', 'Amber', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: 'Nebras Elixir',
    slug: 'nebras-elixir',
    description: 'Nebras Elixir by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2025. The nose behind this fragrance is Nanako Ogi.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img28.png', public_id: '' }],
    notes: { top: ['Milk Candy', 'Whipped Cream'], middle: ['Sugar Cane', 'Heliotrope'], base: ['Vanilla', 'Ambroxan', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: 'Pacific',
    slug: 'pacific',
    description: 'Pacific by Rayhaan is a fragrance for men, launched in 2022.',
    shortDescription: 'Fresh aromatic fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img29.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Lemon', 'Tangerine', 'Cardamom'], middle: ['Lavender', 'Cypress'], base: ['Amber'] },
    tags: ['rayhaan', 'fresh', 'men'],
  },
  {
    name: 'Ameerat Al Arab',
    slug: 'ameerat-al-arab',
    description: 'Ameerat Al Arab (Princess of Arabia) by Asdaaf is a Floral fragrance for women, launched in 2022.',
    shortDescription: 'Floral fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img30.png', public_id: '' }],
    notes: { top: ['Citruses', 'Bergamot'], middle: ['White Musk', 'Aloe Vera'], base: ['Jasmine', 'Musk', 'Woody Notes', 'Oud'] },
    tags: ['asdaaf', 'floral', 'women'],
  },
  {
    name: 'Ameerat Al Arab Prive Rose',
    slug: 'ameerat-al-arab-prive-rose',
    description: 'Ameerat Al Arab Prive Rose (Princess of Arabia Pink) by Asdaaf is a Floral Fruity fragrance for women, launched in 2023.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img31.png', public_id: '' }],
    notes: { top: ['Strawberry', 'Grapes', 'Orange'], middle: ['Rose', 'White Musk', 'Jasmine', 'Gardenia', 'Ylang-Ylang', 'Lily'], base: ['Tonka Bean', 'Amber', 'Sandalwood'] },
    tags: ['asdaaf', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Peace & Love',
    slug: 'peace-and-love',
    description: 'Peace & Love by Lattafa Perfumes is a Floral fragrance for women and men, launched in 2024.',
    shortDescription: 'Floral fragrance for women and men',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img32.png', public_id: '' }],
    notes: { top: ['Almond', 'Black Currant', 'Bergamot'], middle: ['Rose', 'Tuberose'], base: ['Sandalwood', 'Vanilla', 'Heliotrope'] },
    tags: ['lattafa', 'floral', 'unisex'],
  },
  {
    name: 'Amber Oud Bleu Edition',
    slug: 'amber-oud-bleu-edition',
    description: 'Amber Oud Bleu Edition by Al Haramain Perfumes is a fragrance for women and men, launched in 2022.',
    shortDescription: 'Fresh citrus over woody amber',
    price: 100,
    comparePrice: 0,
    gender: 'Unisex',
    size: '60ml',
    stock: 30,
    isFeatured: true,
    images: [{ url: '/products/img33.png', public_id: '' }],
    notes: { top: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'], middle: ['Ginger', 'Vetiver', 'Jasmine'], base: ['Olibanum', 'Sandalwood', 'Cedar', 'Patchouli'] },
    tags: ['al haramain', 'woody', 'unisex'],
  },
  {
    name: 'Delilah pour femme',
    slug: 'delilah-pour-femme',
    description: 'Delilah by Maison Alhambra is a Floral Fruity fragrance for women, launched in 2023.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img34.png', public_id: '' }],
    notes: { top: ['Rhubarb', 'Litchi', 'Bergamot'], middle: ['Turkish Rose', 'Peony', 'Lily'], base: ['White Musk', 'Cashmeran', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Delilah Blanc',
    slug: 'delilah-blanc',
    description: 'Delilah Blanc by Maison Alhambra is a Floral Fruity fragrance for women, launched in 2024.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img35.png', public_id: '' }],
    notes: { top: ['Bergamot', 'White Peach', 'Mandarin'], middle: ['Orange Blossom', 'Vetiver'], base: ['Musk', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Delilah Viola',
    slug: 'delilah-viola',
    description: 'Delilah Viola by Maison Alhambra is a Floral Fruity fragrance for women and men, launched in 2026.',
    shortDescription: 'Floral fruity fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img36.png', public_id: '' }],
    notes: { top: ['Pear', 'Mandarin Orange', 'Bergamot', 'Peach'], middle: ['Lilac', 'Violet', 'Lily of the Valley', 'Lavender'], base: ['White Musk', 'Cream', 'Sandalwood', 'Patchouli', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'unisex'],
  },
  {
    name: 'Liquid Brun',
    slug: 'liquid-brun',
    description: 'Liquid Brun by French Avenue is a Woody fragrance for men, launched in 2024.',
    shortDescription: 'Woody fragrance for men',
    price: 80,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img37.png', public_id: '' }],
    notes: { top: ['Cinnamon', 'Orange Blossom', 'Cardamom', 'Bergamot'], middle: ['Bourbon Vanilla', 'Elemi'], base: ['Praline', 'Ambroxan', 'Musk', 'Guaiac Wood'] },
    tags: ['french avenue', 'woody', 'men'],
  },
  {
    name: 'Asad Zanzibar Limited Edition',
    slug: 'asad-zanzibar-limited-edition',
    description: 'Asad Zanzibar Limited Edition by Lattafa Perfumes is an Oriental Spicy fragrance for men, launched in 2025.',
    shortDescription: 'Oriental spicy fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img38.png', public_id: '' }],
    notes: { top: ['Marine Notes', 'Lavender', 'Pink Pepper'], middle: ['Soap', 'Cashmeran', 'Cinnamon'], base: ['Amber', 'Sandalwood', 'Tonka Bean', 'Cedar'] },
    tags: ['lattafa', 'oriental', 'spicy', 'men'],
  },
  {
    name: 'Yara',
    slug: 'yara',
    description: 'Yara by Lattafa Perfumes is an Oriental Vanilla fragrance for women, launched in 2020.',
    shortDescription: 'Oriental vanilla fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img39.png', public_id: '' }],
    notes: { top: ['Orchid', 'Heliotrope', 'Tangerine'], middle: ['Gourmand Accord', 'Tropical Fruits'], base: ['Vanilla', 'Musk', 'Sandalwood'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'women'],
  },

  // ─── Perfume Note Catalog (54 fragrances) ───
  {
    name: 'Rasasi Hawas Diva', slug: 'rasasi-hawas-diva', description: 'Rasasi Hawas Diva for Women — a fragrance by Rasasi.', shortDescription: 'Red fruits and rose over a warm musk base',
    price: 55, comparePrice: cp(55, 31), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/01_Rasasi_Hawas_Diva.jpg', public_id: '' }],
    notes: { top: ['Red Fruits', 'Lychee', 'Rhubarb'], middle: ['Rose', 'Frankincense', 'Cedar'], base: ['Vanilla', 'Ambergris', 'Musk'] },
    tags: ['rasasi', 'women'],
  },
  {
    name: 'Rasasi Hawas Malibu', slug: 'rasasi-hawas-malibu', description: 'Rasasi Hawas Malibu — a fragrance by Rasasi.', shortDescription: 'Pineapple and citrus over tonka and patchouli',
    price: 60, comparePrice: cp(60, 33), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/02_Rasasi_Hawas_Malibu.jpg', public_id: '' }],
    notes: { top: ['Pineapple', 'Orange', 'Grapefruit'], middle: ['Orris', 'Amber', 'Lavender'], base: ['Tonka Bean', 'Musk', 'Cashmeran', 'Patchouli'] },
    tags: ['rasasi', 'unisex'],
  },
  {
    name: 'Armaf Club de Nuit Woman', slug: 'armaf-club-de-nuit-woman', description: 'Armaf Club de Nuit Woman — a fragrance by Armaf.', shortDescription: 'Bergamot and peach over musk and patchouli',
    price: 48, comparePrice: cp(48, 33), gender: 'For Her', size: '100ml', stock: 30, isBestSeller: true,
    images: [{ url: '/products/03_Armaf_Club_de_Nuit_Woman.jpg', public_id: '' }],
    notes: { top: ['Bergamot', 'Grapefruit', 'Peach', 'Orange'], middle: ['Geranium', 'Jasmine', 'Litchi', 'Rose'], base: ['Musk', 'Patchouli', 'Vanilla', 'Vetiver'] },
    tags: ['armaf', 'women'],
  },
  {
    name: 'Armaf Odyssey Go Mango', slug: 'armaf-odyssey-go-mango', description: 'Armaf Odyssey Go Mango — a fragrance by Armaf.', shortDescription: 'Lemon and ginger over mango and vanilla',
    price: 60, comparePrice: cp(60, 25), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/04_Armaf_Odyssey_Go_Mango.jpg', public_id: '' }],
    notes: { top: ['Lemon', 'Pink Pepper', 'Ginger', 'White Flowers'], middle: ['Mango', 'Tonka Bean', 'Dry Wood'], base: ['Vanilla', 'Amber', 'Guaiac Wood', 'Musk', 'Nutty Notes'] },
    tags: ['armaf', 'unisex'],
  },
  {
    name: 'Armaf Odyssey Mandarin Sky', slug: 'armaf-odyssey-mandarin-sky', description: 'Armaf Odyssey Mandarin Sky — a fragrance by Armaf.', shortDescription: 'Mandarin and saffron over ambroxan and vetiver',
    price: 48, comparePrice: cp(48, 31), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/05_Armaf_Odyssey_Mandarin_Sky.jpg', public_id: '' }],
    notes: { top: ['Mandarin Orange', 'Orange', 'Saffron', 'Sage'], middle: ['Caramel', 'Tonka Bean', 'Marigold'], base: ['Ambroxan', 'Cedar', 'Vetiver'] },
    tags: ['armaf', 'unisex'],
  },
  {
    name: 'Armaf Odyssey Mandarin Sky Elixir', slug: 'armaf-odyssey-mandarin-sky-elixir', description: 'Armaf Odyssey Mandarin Sky Elixir — a fragrance by Armaf.', shortDescription: 'Mandarin and spice over vanilla and vetiver',
    price: 50, comparePrice: cp(50, 44), gender: 'For Him', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/06_Armaf_Odyssey_Mandarin_Sky_Elixir.jpg', public_id: '' }],
    notes: { top: ['Mandarin', 'Orange', 'Lavender', 'Cardamom', 'Black Pepper'], middle: ['Caramel', 'Tonka Bean', 'Patchouli', 'Incense'], base: ['Vanilla', 'Vetiver'] },
    tags: ['armaf', 'men'],
  },
  {
    name: 'Armaf Odyssey Mega Man', slug: 'armaf-odyssey-mega-man', description: 'Armaf Odyssey Mega Man — a fragrance by Armaf.', shortDescription: 'Citrus and mint over cedar and vetiver',
    price: 45, comparePrice: cp(45, 35), gender: 'For Him', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/07_Armaf_Odyssey_Mega_Man.jpg', public_id: '' }],
    notes: { top: ['Lemon', 'Orange', 'Bergamot', 'Ginger', 'Mint'], middle: ['Pineapple', 'Sage', 'Juniper', 'Geranium'], base: ['Musk', 'Cedar', 'Tonka Bean', 'Vetiver'] },
    tags: ['armaf', 'men'],
  },
  {
    name: "Armaf Odyssey Li'chi Lush", slug: 'armaf-odyssey-lichi-lush', description: "Armaf Odyssey Li'chi Lush — a fragrance by Armaf.", shortDescription: 'Litchi and peach over sandalwood and caramel',
    price: 50, comparePrice: 0, gender: 'For Him', size: '100ml', stock: 0,
    images: [{ url: '/products/08_Armaf_Odyssey_Lichi_Lush.jpg', public_id: '' }],
    notes: { top: ['Litchi', 'Mandarin', 'Peach', 'Raspberry'], middle: ['Peony', 'Orange Blossom', 'Magnolia', 'Jasmine', 'Rose', 'Ylang-Ylang'], base: ['Sandalwood', 'Musk', 'Amber', 'Vanilla', 'Caramel'] },
    tags: ['armaf', 'men'],
  },
  {
    name: "Afnan Supremacy Collector's Edition", slug: 'afnan-supremacy-collectors-edition', description: "Afnan Supremacy Collector's Edition — a fragrance by Afnan.", shortDescription: 'Pineapple and bergamot over oak moss and musk',
    price: 70, comparePrice: cp(70, 30), gender: 'For Him', size: '100ml', stock: 30,
    images: [{ url: '/products/09_Afnan_Supremacy_Collectors_Edition.jpg', public_id: '' }],
    notes: { top: ['Pineapple', 'Bergamot', 'Apple', 'White Floral'], middle: ['Orange Blossom', 'Birch', 'Amber'], base: ['Oak Moss', 'Musk', 'Ambergris'] },
    tags: ['afnan', 'men'],
  },
  {
    name: 'Afnan 9PM Night Out', slug: 'afnan-9pm-night-out', description: 'Afnan 9PM Night Out — a fragrance by Afnan.', shortDescription: 'Dragon fruit and cognac over tonka and patchouli',
    price: 70, comparePrice: cp(70, 30), gender: 'For Him', size: '100ml', stock: 30, isBestSeller: true,
    images: [{ url: '/products/10_Afnan_9PM_Night_Out.jpg', public_id: '' }],
    notes: { top: ['Dragon Fruit', 'Bergamot', 'Cognac', 'Lavender', 'Apple'], middle: ['Cardamom', 'Mahonial', 'Suede', 'Toffee', 'Cedar'], base: ['Tonka Bean', 'Akigalawood', 'Ambrofix', 'Patchouli'] },
    tags: ['afnan', 'men'],
  },
  {
    name: 'Afnan 9PM Ultimate Twist', slug: 'afnan-9pm-ultimate-twist', description: 'Afnan 9PM Ultimate Twist — a fragrance by Afnan.', shortDescription: 'Apple and cinnamon over vanilla and amber',
    price: 40, comparePrice: cp(40, 27), gender: 'For Him', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/11_Afnan_9PM_Ultimate_Twist.jpg', public_id: '' }],
    notes: { top: ['Apple', 'Cinnamon', 'Wild Lavender', 'Bergamot'], middle: ['Orange Blossom', 'Lily-of-the-Valley'], base: ['Vanilla', 'Tonka Bean', 'Amber', 'Patchouli'] },
    tags: ['afnan', 'men'],
  },
  {
    name: 'Afnan Mystique Bouquet', slug: 'afnan-mystique-bouquet', description: 'Afnan Mystique Bouquet — a fragrance by Afnan.', shortDescription: 'White peach and bergamot over ambroxan and musk',
    price: 65, comparePrice: cp(65, 27), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/12_Afnan_Mystique_Bouquet.jpg', public_id: '' }],
    notes: { top: ['White Peach', 'Mandarin Orange', 'Bergamot', 'Litchi'], middle: ['Orange Blossom', 'Vetiver', 'Mahonia', 'Peony'], base: ['Ambroxan', 'Musk', 'Vanilla', 'Oak Moss'] },
    tags: ['afnan', 'women'],
  },
  {
    name: 'Zimaya Sharaf Blend', slug: 'zimaya-sharaf-blend', description: 'Zimaya Sharaf Blend — a fragrance by Zimaya.', shortDescription: 'Dates and saffron over tonka and benzoin',
    price: 50, comparePrice: cp(50, 16), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/13_Zimaya_Sharaf_Blend.jpg', public_id: '' }],
    notes: { top: ['Dates', 'Nutmeg', 'Saffron'], middle: ['Vanilla', 'Praline', 'Tuberose'], base: ['Tonka Bean', 'Amberwood', 'Benzoin', 'Musk'] },
    tags: ['zimaya', 'unisex'],
  },
  {
    name: 'Khadlaj Island Dreams', slug: 'khadlaj-island-dreams', description: 'Khadlaj Island Dreams — a fragrance by Khadlaj.', shortDescription: 'Ginger and bergamot over musk and ambroxan',
    price: 65, comparePrice: cp(65, 27), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/14_Khadlaj_Island_Dreams.jpg', public_id: '' }],
    notes: { top: ['Ginger', 'Bergamot'], middle: ['Grapefruit'], base: ['Musk', 'Ambroxan'] },
    tags: ['khadlaj', 'unisex'],
  },
  {
    name: 'Khadlaj Island', slug: 'khadlaj-island', description: 'Khadlaj Island — a fragrance by Khadlaj.', shortDescription: 'Pineapple and ginger over sandalwood and amber',
    price: 50, comparePrice: cp(50, 37), gender: 'Unisex', size: '100ml', stock: 30, isBestSeller: true,
    images: [{ url: '/products/15_Khadlaj_Island.jpg', public_id: '' }],
    notes: { top: ['Pineapple', 'Iris', 'Ginger', 'Cypress'], middle: ['Coconut', 'Woody Notes'], base: ['Tonka', 'Sandalwood', 'Amber', 'Ambergris'] },
    tags: ['khadlaj', 'unisex'],
  },
  {
    name: 'Khadlaj Island Vanilla Dunes', slug: 'khadlaj-island-vanilla-dunes', description: 'Khadlaj Island Vanilla Dunes — a fragrance by Khadlaj.', shortDescription: 'Vanilla and cardamom over praline and musk',
    price: 50, comparePrice: cp(50, 28), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/16_Khadlaj_Island_Vanilla_Dunes.jpg', public_id: '' }],
    notes: { top: ['Vanilla', 'Cinnamon', 'Cardamom', 'Bergamot'], middle: ['Orange Blossom', 'Guaiac Wood'], base: ['Praline', 'Amber', 'Musk'] },
    tags: ['khadlaj', 'unisex'],
  },
  {
    name: 'Khadlaj Sawaar Vanille Blanc', slug: 'khadlaj-sawaar-vanille-blanc', description: 'Khadlaj Sawaar Vanille Blanc — a fragrance by Khadlaj.', shortDescription: 'Vanilla and apple over sandalwood and benzoin',
    price: 65, comparePrice: cp(65, 27), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/17_Khadlaj_Sawaar_Vanille_Blanc.jpg', public_id: '' }],
    notes: { top: ['Vanilla', 'Powdered Sugar', 'Apple'], middle: ['Cashmere Wood', 'Amber', 'White Blossom'], base: ['Vanilla', 'Sandalwood', 'Benzoin'] },
    tags: ['khadlaj', 'women'],
  },
  {
    name: 'Khadlaj Karus Cream Velvet', slug: 'khadlaj-karus-cream-velvet', description: 'Khadlaj Karus Cream Velvet — a fragrance by Khadlaj.', shortDescription: 'Caramel and butter over vanilla and musk',
    price: 55, comparePrice: cp(55, 31), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/18_Khadlaj_Karus_Cream_Velvet.jpg', public_id: '' }],
    notes: { top: ['Caramel', 'Butter'], middle: ['Tonka', 'Honey', 'Jasmine'], base: ['Vanilla', 'Musk', 'Amber'] },
    tags: ['khadlaj', 'unisex'],
  },
  {
    name: 'Khadlaj Panache Angel Dust', slug: 'khadlaj-panache-angel-dust', description: 'Khadlaj Panache Angel Dust — a fragrance by Khadlaj.', shortDescription: 'Vanilla and red currant over whipped cream and musk',
    price: 60, comparePrice: cp(60, 33), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/19_Khadlaj_Panache_Angel_Dust.jpg', public_id: '' }],
    notes: { top: ['Vanilla', 'Mandarin', 'Red Currant'], middle: ['Tuberose', 'Sandalwood', 'Rum'], base: ['Vanilla', 'Whipped Cream', 'Musk', 'Benzoin'] },
    tags: ['khadlaj', 'women'],
  },
  {
    name: 'Khadlaj Icon (2026)', slug: 'khadlaj-icon-2026', description: 'Khadlaj Icon (2026) — a fragrance by Khadlaj.', shortDescription: 'Bergamot and incense over amber and sandalwood',
    price: 65, comparePrice: cp(65, 27), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/20_Khadlaj_Icon_2026.jpg', public_id: '' }],
    notes: { top: ['Bergamot'], middle: ['Labdanum', 'Incense', 'Lavender'], base: ['Amber', 'Suede', 'Sandalwood'] },
    tags: ['khadlaj', 'unisex'],
  },
  {
    name: 'Rayhaan Divine', slug: 'rayhaan-divine', description: 'Rayhaan Divine — a fragrance by Rayhaan.', shortDescription: 'Litchi and ginger over patchouli and chocolate',
    price: 55, comparePrice: cp(55, 31), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/21_Rayhaan_Divine.jpg', public_id: '' }],
    notes: { top: ['Litchi', 'Ginger', 'Bergamot'], middle: ['Peony', 'Rose', 'Vanilla'], base: ['Patchouli', 'Chocolate'] },
    tags: ['rayhaan', 'women'],
  },
  {
    name: 'French Avenue Vulcan Feu', slug: 'french-avenue-vulcan-feu', description: 'French Avenue Vulcan Feu — a fragrance by French Avenue.', shortDescription: 'Mango and ginger over tonka and ambergris',
    price: 60, comparePrice: cp(60, 33), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/22_French_Avenue_Vulcan_Feu.jpg', public_id: '' }],
    notes: { top: ['Mango', 'Lemon', 'Ginger', 'Rhubarb'], middle: ['Jasmine', 'Pink Pepper', 'Violet', 'Praline'], base: ['Tonka Bean', 'Cedarwood', 'Ambergris', 'Moss'] },
    tags: ['french avenue', 'unisex'],
  },
  {
    name: 'French Avenue Tropical Kiss', slug: 'french-avenue-tropical-kiss', description: 'French Avenue Tropical Kiss — a fragrance by French Avenue.', shortDescription: 'Chamomile and mango over vanilla and benzoin',
    price: 55, comparePrice: 0, gender: 'Unisex', size: '100ml', stock: 0,
    images: [{ url: '/products/23_French_Avenue_Tropical_Kiss.jpg', public_id: '' }],
    notes: { top: ['Chamomile', 'Mango', 'Orange Blossom'], middle: ['Ylang-Ylang', 'Coconut', 'Orris'], base: ['Vanilla', 'Amber', 'Benzoin'] },
    tags: ['french avenue', 'unisex'],
  },
  {
    name: 'Riiffs Taif', slug: 'riiffs-taif', description: 'Riiffs Taif — a fragrance by Riiffs.', shortDescription: 'Ginger and orange blossom over vanilla bean and amberwood',
    price: 50, comparePrice: cp(50, 28), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/24_Riiffs_Taif.jpg', public_id: '' }],
    notes: { top: ['Ginger', 'Lemon', 'Calabrian Bergamot', 'Orange Blossom'], middle: ['Musk', 'Rose Petals', 'Tuberose'], base: ['Vanilla Bean', 'Clearwood', 'Amberwood'] },
    tags: ['riiffs', 'women'],
  },
  {
    name: 'Riiffs Zenith', slug: 'riiffs-zenith', description: 'Riiffs Zenith — a fragrance by Riiffs.', shortDescription: 'Vanilla and coconut over musk and woody notes',
    price: 55, comparePrice: cp(55, 31), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/25_Riiffs_Zenith.jpg', public_id: '' }],
    notes: { top: ['Vanilla', 'Creamy Notes', 'Coconut'], middle: ['Fruity Notes', 'Powdery Notes', 'Jasmine'], base: ['Vanilla', 'Musk', 'Woody Notes'] },
    tags: ['riiffs', 'unisex'],
  },
  {
    name: 'Lattafa Her Confession', slug: 'lattafa-her-confession', description: 'Lattafa Her Confession — a fragrance by Lattafa.', shortDescription: 'Cinnamon and jasmine over tonka and vanilla',
    price: 55, comparePrice: cp(55, 31), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/26_Lattafa_Her_Confession.jpg', public_id: '' }],
    notes: { top: ['Mystikal Accord', 'Cinnamon'], middle: ['Jasmine', 'Tuberose', 'Incense', 'Mahonial'], base: ['Tonka Beans', 'Musk', 'Vanilla'] },
    tags: ['lattafa', 'women'],
  },
  {
    name: 'Lattafa Pride Peace & Love', slug: 'lattafa-pride-peace-love', description: 'Lattafa Pride Peace & Love — a fragrance by Lattafa.', shortDescription: 'Bergamot and almond over sandalwood and vanilla',
    price: 65, comparePrice: 0, gender: 'Unisex', size: '100ml', stock: 0,
    images: [{ url: '/products/27_Lattafa_Pride_Peace_Love.jpg', public_id: '' }],
    notes: { top: ['Bergamot', 'Almond', 'Blackcurrant'], middle: ['Rose', 'Tuberose'], base: ['Sandalwood', 'Heliotrope', 'Vanilla'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Angham Second Song', slug: 'lattafa-angham-second-song', description: 'Lattafa Angham Second Song — a fragrance by Lattafa.', shortDescription: 'Pear blossom and bergamot over vanilla and ambroxan',
    price: 55, comparePrice: cp(55, 31), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/28_Lattafa_Angham_Second_Song.jpg', public_id: '' }],
    notes: { top: ['Pear Blossom', 'Bergamot'], middle: ['Peony', 'Praline', 'Orange Blossom'], base: ['Vanilla', 'Musk', 'Tonka', 'Ambroxan'] },
    tags: ['lattafa', 'women'],
  },
  {
    name: 'Lattafa Tharwah Gold', slug: 'lattafa-tharwah-gold', description: 'Lattafa Tharwah Gold — a fragrance by Lattafa.', shortDescription: 'Lavender and bergamot over vanilla and vetiver',
    price: 55, comparePrice: cp(55, 31), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/29_Lattafa_Tharwah_Gold.jpg', public_id: '' }],
    notes: { top: ['Lavender', 'Bergamot'], middle: ['Orange Blossom', 'Egyptian Jasmine'], base: ['Vanilla', 'Amber', 'Vetiver'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Ana Abiyedh Passion', slug: 'lattafa-ana-abiyedh-passion', description: 'Lattafa Ana Abiyedh Passion — a fragrance by Lattafa.', shortDescription: 'Passionfruit and bergamot over tonka and ambrofix',
    price: 55, comparePrice: cp(55, 21), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/30_Lattafa_Ana_Abiyedh_Passion.jpg', public_id: '' }],
    notes: { top: ['Passionfruit', 'Bergamot'], middle: ['Cashmeran', 'Rosyfolia', 'Mahonial'], base: ['Vanilla', 'Musk', 'Tonka Bean', 'Ambrofix'] },
    tags: ['lattafa', 'women'],
  },
  {
    name: 'Lattafa Khamrah', slug: 'lattafa-khamrah', description: 'Lattafa Khamrah — a fragrance by Lattafa.', shortDescription: 'Cinnamon and dates over amberwood and myrrh',
    price: 50, comparePrice: cp(50, 16), gender: 'Unisex', size: '100ml', stock: 30, isBestSeller: true,
    images: [{ url: '/products/31_Lattafa_Khamrah.jpg', public_id: '' }],
    notes: { top: ['Cinnamon', 'Nutmeg', 'Bergamot'], middle: ['Dates', 'Praline', 'Tuberose', 'Mahonial'], base: ['Vanilla', 'Tonka Bean', 'Amberwood', 'Myrrh', 'Benzoin', 'Akigalawood'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Eclaire', slug: 'lattafa-eclaire', description: 'Lattafa Eclaire — a fragrance by Lattafa.', shortDescription: 'Caramel and milk over vanilla and musk',
    price: 50, comparePrice: cp(50, 28), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/32_Lattafa_Eclaire.jpg', public_id: '' }],
    notes: { top: ['Caramel', 'Milk', 'Sugar'], middle: ['Honey', 'White Flowers'], base: ['Vanilla', 'Praline', 'Musk'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Yara Elixir', slug: 'lattafa-yara-elixir', description: 'Lattafa Yara Elixir — a fragrance by Lattafa.', shortDescription: 'Strawberry s\'mores and black currant over vanilla and amber',
    price: 50, comparePrice: cp(50, 37), gender: 'For Her', size: '100ml', stock: 30,
    images: [{ url: '/products/33_Lattafa_Yara_Elixir.jpg', public_id: '' }],
    notes: { top: ['Strawberry S\'mores', 'Black Currant'], middle: ['Jasmine', 'Orange Flower'], base: ['Vanilla', 'Caramel', 'Amber', 'Musk'] },
    tags: ['lattafa', 'women'],
  },
  {
    name: "Lattafa Bade'e Al Oud Amethyst", slug: 'lattafa-badee-al-oud-amethyst', description: "Lattafa Bade'e Al Oud Amethyst — a fragrance by Lattafa.", shortDescription: 'Pink pepper and rose over agarwood and vanilla',
    price: 40, comparePrice: cp(40, 33), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/34_Lattafa_Badee_Al_Oud_Amethyst.jpg', public_id: '' }],
    notes: { top: ['Pink Pepper', 'Bergamot'], middle: ['Turkish Rose', 'Bulgarian Rose', 'Jasmine'], base: ['Agarwood (Oud)', 'Amber', 'Vanilla'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa The Kingdom', slug: 'lattafa-the-kingdom', description: 'Lattafa The Kingdom — a fragrance by Lattafa.', shortDescription: 'Pear and black currant over sandalwood and amber',
    price: 45, comparePrice: cp(45, 35), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/35_Lattafa_The_Kingdom.jpg', public_id: '' }],
    notes: { top: ['Pear', 'Black Currant', 'Peony'], middle: ['Jasmine', 'Praline', 'Tonka Bean'], base: ['Musk', 'Vanilla', 'Sandalwood', 'Amber'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Petra', slug: 'lattafa-petra', description: 'Lattafa Petra — a fragrance by Lattafa.', shortDescription: 'Plum and rum over praline and vanilla',
    price: 50, comparePrice: 0, gender: 'Unisex', size: '100ml', stock: 0,
    images: [{ url: '/products/36_Lattafa_Petra.jpg', public_id: '' }],
    notes: { top: ['Plum', 'Rum'], middle: ['Tuberose', 'Coconut'], base: ['Praline', 'Musk', 'Vanilla'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Lattafa Habik', slug: 'lattafa-habik', description: 'Lattafa Habik — a fragrance by Lattafa.', shortDescription: 'Bergamot and pear over musk and oakmoss',
    price: 40, comparePrice: cp(40, 33), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/37_Lattafa_Habik.jpg', public_id: '' }],
    notes: { top: ['Bergamot', 'Pear'], middle: ['Jasmine', 'Lily of the Valley', 'Freesia'], base: ['Musk', 'Dry Amber', 'Oakmoss'] },
    tags: ['lattafa', 'unisex'],
  },
  {
    name: 'Maison Alhambra Leonie Intense', slug: 'maison-alhambra-leonie-intense', description: 'Maison Alhambra Leonie Intense — a fragrance by Maison Alhambra.', shortDescription: 'Lavender and blackcurrant over vanilla and cedar',
    price: 55, comparePrice: 0, gender: 'Unisex', size: '100ml', stock: 0,
    images: [{ url: '/products/38_Maison_Alhambra_Leonie_Intense.jpg', public_id: '' }],
    notes: { top: ['Lavender', 'Blackcurrant', 'Petitgrain', 'Tangerine'], middle: ['Orange Blossom', 'Lavender', 'Jasmine'], base: ['Madagascar Vanilla', 'Amber', 'Cedar', 'Musk'] },
    tags: ['maison alhambra', 'unisex'],
  },
  {
    name: 'Paris Corner Marshmallow Blush', slug: 'paris-corner-marshmallow-blush', description: 'Paris Corner Marshmallow Blush — a fragrance by Paris Corner.', shortDescription: 'Strawberry and raspberry over marshmallow and vanilla',
    price: 30, comparePrice: cp(30, 25), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/39_Paris_Corner_Marshmallow_Blush.jpg', public_id: '' }],
    notes: { top: ['Strawberry', 'Raspberry', 'Lemon'], middle: ['Ambroxan', 'Orange Blossom', 'Whipped Cream'], base: ['Musk', 'Marshmallow', 'Vanilla'] },
    tags: ['paris corner', 'unisex'],
  },
  {
    name: 'French Avenue Safari Breeze', slug: 'french-avenue-safari-breeze', description: 'French Avenue Safari Breeze — a fragrance by French Avenue.', shortDescription: 'Grapefruit and coconut over vetiver and oakmoss',
    price: 55, comparePrice: cp(55, 38), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/40_French_Avenue_Safari_Breeze.jpg', public_id: '' }],
    notes: { top: ['Grapefruit', 'Blackcurrant', 'Coconut'], middle: ['Spearmint', 'Jasmine'], base: ['Vetiver', 'Amber', 'Oakmoss'] },
    tags: ['french avenue', 'unisex'],
  },
  {
    name: 'Ghali Elegant EDP', slug: 'ghali-elegant-edp', description: 'Ghali Elegant EDP — a fragrance by Ghali.', shortDescription: 'Orange and pear over wood and sandalwood',
    price: 65, comparePrice: 0, gender: 'For Her', size: '100ml', stock: 0,
    images: [{ url: '/products/41_Ghali_Elegant_EDP.jpg', public_id: '' }],
    notes: { top: ['Orange', 'Pear', 'Bergamot'], middle: ['Rose', 'Orange Flower', 'Saffron', 'Musk'], base: ['Wood', 'Amber', 'Vanilla', 'Sandalwood'] },
    tags: ['ghali', 'women'],
  },
  {
    name: 'Nectar of Ecstasy', slug: 'nectar-of-ecstasy', description: 'Nectar of Ecstasy — a fruity floral fragrance.', shortDescription: 'Acai berry and blueberry over vanilla and caramel',
    price: 30, comparePrice: cp(30, 40), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/42_Nectar_of_Ecstasy.jpg', public_id: '' }],
    notes: { top: ['Acai Berry', 'Blueberry'], middle: ['Freesia', 'Bergamot'], base: ['Vanilla', 'Caramel', 'Musk'] },
    tags: ['fruity', 'women'],
  },
  {
    name: 'Bouquet of Euphoria', slug: 'bouquet-of-euphoria', description: 'Bouquet of Euphoria — a floral gourmand fragrance.', shortDescription: 'Heliotrope and candied fruits over vanilla and musk',
    price: 30, comparePrice: cp(30, 40), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/43_Bouquet_of_Euphoria.jpg', public_id: '' }],
    notes: { top: ['Heliotrope', 'Candied Fruits'], middle: ['Gardenia', 'Jasmine', 'Sandalwood'], base: ['Vanilla', 'Caramel', 'Musk'] },
    tags: ['floral', 'women'],
  },
  {
    name: 'Creme of Clouds', slug: 'creme-of-clouds', description: 'Creme of Clouds — a gourmand fragrance.', shortDescription: 'Whipped cream and burnt sugar over vanilla',
    price: 50, comparePrice: cp(50, 37), gender: 'For Her', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/44_Creme_of_Clouds.jpg', public_id: '' }],
    notes: { top: ['Whipped Cream', 'Burnt Sugar'], middle: ['Coconut Milk'], base: ['Vanilla'] },
    tags: ['gourmand', 'women'],
  },
  {
    name: 'Platine Blanc', slug: 'platine-blanc', description: 'Platine Blanc — a fresh aromatic fragrance.', shortDescription: 'Mint and lime over sandalwood and oakmoss',
    price: 70, comparePrice: cp(70, 30), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/45_Platine_Blanc.jpg', public_id: '' }],
    notes: { top: ['Mint', 'Lime', 'Tonic Water', 'Lemon'], middle: ['Rosemary', 'Black Currant', 'Jasmine'], base: ['Musk', 'Ambergris', 'Sandalwood', 'Oakmoss'] },
    tags: ['fresh', 'unisex'],
  },
  {
    name: 'Eshal Vanilla', slug: 'eshal-vanilla', description: 'Eshal Vanilla by Paris Corner — a gourmand fragrance.', shortDescription: 'Sugary notes over vanilla, caramel and musk',
    price: 40, comparePrice: 0, gender: 'Unisex', size: '100ml', stock: 0,
    images: [{ url: '/products/46_Eshal_Vanilla.jpg', public_id: '' }],
    notes: { top: ['Sugar'], middle: ['Rose', 'Jasmine'], base: ['Vanilla', 'Caramel', 'Musk'] },
    tags: ['paris corner', 'gourmand', 'unisex'],
  },
  {
    name: 'Mango Ice', slug: 'mango-ice', description: 'Mango Ice — a fruity fragrance.', shortDescription: 'Ginger and mango over cedarwood and ambergris',
    price: 40, comparePrice: cp(40, 33), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/47_Mango_Ice.jpg', public_id: '' }],
    notes: { top: ['Ginger', 'Mango', 'Lemon', 'Rhubarb'], middle: ['Jasmine', 'Violet', 'Praline', 'Pink Pepper'], base: ['Cedarwood', 'Ambergris', 'Tonka Beans', 'Moss'] },
    tags: ['fruity', 'unisex'],
  },
  {
    name: 'Milky Way', slug: 'milky-way', description: 'Milky Way by Maison Alhambra — a gourmand fragrance.', shortDescription: 'Sweet milk and caramel over tonka and sandalwood',
    price: 60, comparePrice: cp(60, 25), gender: 'Unisex', size: '100ml', stock: 0, isNewArrival: true,
    images: [{ url: '/products/48_Milky_Way.jpg', public_id: '' }],
    notes: { top: ['Sweet Milk', 'Caramel', 'Plum'], middle: ['Ylang-Ylang', 'Jasmine', 'Orris', 'Cashmere'], base: ['Tonka Beans', 'Vanilla', 'Sandalwood'] },
    tags: ['maison alhambra', 'gourmand', 'unisex'],
  },
  {
    name: 'Mahd Al Dhahab', slug: 'mahd-al-dhahab', description: 'Mahd Al Dhahab by Arabiyat Prestige — a fragrance.', shortDescription: 'Bergamot and spices over sandalwood and white musk',
    price: 65, comparePrice: cp(65, 27), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/49_Mahd_Al_Dhahab.jpg', public_id: '' }],
    notes: { top: ['Bergamot', 'Spices', 'Lemon'], middle: ['Amber', 'Patchouli', 'Oud'], base: ['Vanilla', 'Sandalwood', 'White Musk'] },
    tags: ['arabiyat prestige', 'unisex'],
  },
  {
    name: 'The White Cloud', slug: 'the-white-cloud', description: 'The White Cloud by Maison Alhambra — a fragrance.', shortDescription: 'Bitter almond over vanilla absolute and sandalwood',
    price: 40, comparePrice: cp(40, 33), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/50_The_White_Cloud.jpg', public_id: '' }],
    notes: { top: ['Bitter Almond'], middle: ['Vanilla', 'Floral Notes'], base: ['Vanilla Absolute', 'Tonka Bean', 'Sandalwood'] },
    tags: ['maison alhambra', 'unisex'],
  },
  {
    name: 'Jean Lowe Azure', slug: 'jean-lowe-azure', description: 'Jean Lowe Azure by Maison Alhambra — a fresh fragrance.', shortDescription: 'Mandarin and bergamot over ginger and ambergris',
    price: 50, comparePrice: cp(50, 28), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/51_Jean_Lowe_Azure.jpg', public_id: '' }],
    notes: { top: ['Mandarin', 'Bergamot'], middle: ['Orange'], base: ['Ginger', 'Ambergris'] },
    tags: ['jean lowe', 'unisex'],
  },
  {
    name: 'Jean Lowe Vibe', slug: 'jean-lowe-vibe', description: 'Jean Lowe Vibe by Maison Alhambra — a fresh fragrance.', shortDescription: 'Mint and citron over fig and dates',
    price: 50, comparePrice: cp(50, 28), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/52_Jean_Lowe_Vibe.jpg', public_id: '' }],
    notes: { top: ['Mint', 'Citron', 'Lemon', 'Orange', 'Black Currant', 'Coriander'], middle: ['Apricot', 'Basil', 'May Rose', 'Carrot Seeds'], base: ['Fig', 'Ambrette', 'Dates'] },
    tags: ['jean lowe', 'unisex'],
  },
  {
    name: 'Jean Lowe Immortal', slug: 'jean-lowe-immortal', description: 'Jean Lowe Immortal by Maison Alhambra — a fresh fragrance.', shortDescription: 'Ginger and grapefruit over ambroxan and labdanum',
    price: 45, comparePrice: cp(45, 35), gender: 'Unisex', size: '100ml', stock: 30,
    images: [{ url: '/products/53_Jean_Lowe_Immortal.jpg', public_id: '' }],
    notes: { top: ['Ginger', 'Grapefruit', 'Bergamot'], middle: ['Rosemary', 'Water Notes', 'Sage', 'Geranium'], base: ['Ambroxan', 'Amber', 'Labdanum'] },
    tags: ['jean lowe', 'unisex'],
  },
  {
    name: 'Marwa Arabiyat Prestige', slug: 'marwa-arabiyat-prestige', description: 'Marwa by Arabiyat Prestige — a fragrance for Unisex.', shortDescription: 'Calabrian bergamot and neroli over black tea and guaiac wood',
    price: 65, comparePrice: cp(65, 27), gender: 'Unisex', size: '100ml', stock: 30, isBestSeller: true,
    images: [{ url: '/products/54_Marwa_Arabiyat_Prestige.jpg', public_id: '' }],
    notes: { top: ['Calabrian Bergamot', 'Lemon', 'Sicilian Orange'], middle: ['Nigerian Ginger', 'Ceylon Cinnamon', 'Tunisian Neroli'], base: ['Ambroxan', 'Chinese Black Tea', 'Olibanum', 'Guaiac Wood'] },
    tags: ['arabiyat prestige', 'unisex'],
  },

  // ─── For Decant — Original Brand (10ml decants, 10% off) ───
  {
    name: 'Burberry Goddess', slug: 'burberry-goddess-decant', description: 'Burberry Goddess — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 55, comparePrice: cp(55, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'burberry', 'women'],
    images: [{ url: '/products/55_Burberry_Goddess.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Prada Paradoxe Intense', slug: 'prada-paradoxe-intense-decant', description: 'Prada Paradoxe Intense — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'prada', 'women'],
    images: [{ url: '/products/56_Prada_Paradoxe_Intense.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'D&G Light Blue', slug: 'dg-light-blue-decant', description: 'D&G Light Blue — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 49, comparePrice: cp(49, 10), gender: 'For Her', size: '10ml', stock: 30, isBestSeller: true, tags: ['decant', 'dolce gabbana', 'women'],
    images: [{ url: '/products/57_DG_Light_Blue.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'YSL Libre Intense', slug: 'ysl-libre-intense-decant', description: 'YSL Libre Intense — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 49, comparePrice: cp(49, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'ysl', 'women'],
    images: [{ url: '/products/58_YSL_Libre_Intense.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Carolina Herrera Good Girl', slug: 'carolina-herrera-good-girl-decant', description: 'Carolina Herrera Good Girl — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 46, comparePrice: cp(46, 10), gender: 'For Her', size: '10ml', stock: 30, isBestSeller: true, tags: ['decant', 'carolina herrera', 'women'],
    images: [{ url: '/products/59_Carolina_Herrera_Good_Girl.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Valentino Born In Roma Extradose', slug: 'valentino-born-in-roma-extradose-decant', description: 'Valentino Born In Roma Extradose — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'valentino', 'women'],
    images: [{ url: '/products/60_Valentino_Born_In_Roma_Extradose.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Valentino Born In Roma Donna', slug: 'valentino-born-in-roma-donna-decant', description: 'Valentino Born In Roma Donna — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 48, comparePrice: cp(48, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'valentino', 'women'],
    images: [{ url: '/products/61_Valentino_Born_In_Roma_Donna.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Valentina', slug: 'valentina-decant', description: 'Valentina by Valentino — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 45, comparePrice: cp(45, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'valentino', 'women'],
    images: [{ url: '/products/62_Valentina.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Flowerbomb EDP', slug: 'flowerbomb-edp-decant', description: 'Flowerbomb EDP by Viktor&Rolf — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, isBestSeller: true, tags: ['decant', 'viktor rolf', 'women'],
    images: [{ url: '/products/63_Flowerbomb_EDP.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Flowerbomb Tiger Lily', slug: 'flowerbomb-tiger-lily-decant', description: 'Flowerbomb Tiger Lily by Viktor&Rolf — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'viktor rolf', 'women'],
    images: [{ url: '/products/64_Flowerbomb_Tiger_Lily.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Flowerbomb Ruby Orchid', slug: 'flowerbomb-ruby-orchid-decant', description: 'Flowerbomb Ruby Orchid by Viktor&Rolf — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'viktor rolf', 'women'],
    images: [{ url: '/products/65_Flowerbomb_Ruby_Orchid.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Flowerbomb Nectar', slug: 'flowerbomb-nectar-decant', description: 'Flowerbomb Nectar by Viktor&Rolf — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 50, comparePrice: cp(50, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'viktor rolf', 'women'],
    images: [{ url: '/products/66_Flowerbomb_Nectar.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'YSL Libre', slug: 'ysl-libre-decant', description: 'YSL Libre — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 48, comparePrice: cp(48, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'ysl', 'women'],
    images: [{ url: '/products/67_YSL_Libre.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Emporio Armani Because of You', slug: 'emporio-armani-because-of-you-decant', description: 'Emporio Armani Because of You — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 40, comparePrice: cp(40, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'armani', 'women'],
    images: [{ url: '/products/68_Emporio_Armani_Because_of_You.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Replica When the Rain Stops', slug: 'replica-when-the-rain-stops-decant', description: 'Replica When the Rain Stops by Maison Margiela — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 46, comparePrice: cp(46, 10), gender: 'Unisex', size: '10ml', stock: 30, tags: ['decant', 'maison margiela', 'unisex'],
    images: [{ url: '/products/69_Replica_When_the_Rain_Stops.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Mugler Angel EDP Blue', slug: 'mugler-angel-edp-blue-decant', description: 'Mugler Angel EDP (Blue) — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 47, comparePrice: cp(47, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'mugler', 'women'],
    images: [{ url: '/products/70_Mugler_Angel_EDP_Blue.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'BLV II Bvlgari EDP', slug: 'blv-ii-bvlgari-edp-decant', description: 'BLV II by Bvlgari — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 45, comparePrice: cp(45, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'bvlgari', 'women'],
    images: [{ url: '/products/71_BLV_II_Bvlgari_EDP.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Prada Milano Infusion', slug: 'prada-milano-infusion-decant', description: 'Prada Milano Infusion — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 45, comparePrice: cp(45, 10), gender: 'Unisex', size: '10ml', stock: 30, tags: ['decant', 'prada', 'unisex'],
    images: [{ url: '/products/72_Prada_Milano_Infusion.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Chloe Love', slug: 'chloe-love-decant', description: 'Love by Chloé — 10ml decant of the original designer perfume.', shortDescription: 'Original brand decant, 10ml',
    price: 45, comparePrice: cp(45, 10), gender: 'For Her', size: '10ml', stock: 30, tags: ['decant', 'chloe', 'women'],
    images: [{ url: '/products/73_Chloe_Love.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'Dior Sauvage',  slug: 'dior-sauvage-man-decant', description: 'Dior Sauvage — 10ml decant of the original designer perfume for men.', shortDescription: 'Original brand decant, 10ml',
    price: 48, comparePrice: 0, gender: 'For Him', size: '10ml', stock: 0, tags: ['decant', 'dior', 'men'],
    images: [{ url: '/products/74_Dior_Sauvage_Man.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
  {
    name: 'YSL Y EDP', slug: 'ysl-y-edp-man-decant', description: 'YSL Y EDP — 10ml decant of the original designer perfume for men.', shortDescription: 'Original brand decant, 10ml',
    price: 48, comparePrice: 0, gender: 'For Him', size: '10ml', stock: 0, tags: ['decant', 'ysl', 'men'],
    images: [{ url: '/products/75_YSL_Y_EDP_Man.jpg', public_id: '' }], notes: { top: [], middle: [], base: [] },
  },
];

const seed = async () => {
  try {
    await connectDB();

    // 1. Admin user
    const adminEmail = process.env.SEED_ADMIN_EMAIL || 'admin@fusionscent.com';
    const adminPassword = process.env.SEED_ADMIN_PASSWORD || 'Admin@12345';

    let admin = await User.findOne({ email: adminEmail });
    if (!admin) {
      admin = await User.create({
        name: 'FusionScent Admin',
        email: adminEmail,
        password: adminPassword,
        role: 'admin',
      });
      console.log(`Admin created -> email: ${adminEmail} | password: ${adminPassword}`);
    } else {
      console.log(`Admin already exists -> ${adminEmail}`);
    }

    // 2. Categories
    const categoryMap = {};
    for (const cat of categoriesData) {
      let existing = await Category.findOne({ slug: cat.slug });
      if (!existing) {
        existing = await Category.create(cat);
        console.log(`Category created: ${cat.name}`);
      }
      categoryMap[cat.name] = existing._id;
    }

    // 3. Remove old placeholder products
    const removed = await Product.deleteMany({ slug: { $in: legacySlugs } });
    if (removed.deletedCount) console.log(`Removed ${removed.deletedCount} legacy placeholder product(s)`);

    // 4. Products
    for (const prod of productsData) {
      const existing = await Product.findOne({ slug: prod.slug });
      if (existing) {
        console.log(`Product already exists: ${prod.name}`);
        continue;
      }
      const categoryId = categoryMap[prod.gender] || categoryMap['Unisex'];
      await Product.create({ ...prod, category: categoryId });
      console.log(`Product created: ${prod.name}`);
    }

    console.log('Seeding complete.');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seed();
