const dotenv = require('dotenv');
const mongoose = require('mongoose');
const connectDB = require('./config/db');
const User = require('./models/User');
const Category = require('./models/Category');
const Product = require('./models/Product');

dotenv.config();

const categoriesData = [
  { name: 'For Her', slug: 'for-her', description: 'Elegant fragrances crafted for her' },
  { name: 'For Him', slug: 'for-him', description: 'Bold fragrances crafted for him' },
  { name: 'Unisex', slug: 'unisex', description: 'Fragrances for everyone' },
];

// Products no longer sold — deleted from the DB on seed if present
const legacySlugs = ['velvet-rose', 'midnight-oud', 'citrus-breeze', 'golden-amber'];

const productsData = [
  {
    name: 'The Story Sport',
    slug: 'the-story-sport',
    description: 'The Story Sport by Le Bonheur Perfumes is a refreshing Eau de Parfum created for those who embrace movement, ambition, and new beginnings. Blending vibrant citrus notes with aromatic florals and a warm woody base, this energetic fragrance delivers a clean and uplifting scent that is perfect for active days and warm-weather occasions.',
    shortDescription: 'Vibrant citrus with an aromatic floral-woody base',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img1.png', public_id: '' }],
    notes: { top: ['Grapefruit', 'Bergamot', 'Lemon'], middle: ['Fig', 'Jasmine', 'Pink Pepper'], base: ['Cedarwood', 'Benzoin', 'Amber'] },
    tags: ['le bonheur', 'citrus', 'woody', 'unisex'],
  },
  {
    name: 'Black Cavalier Surge',
    slug: 'black-cavalier-surge',
    description: "Black Cavalier Surge by Le Bonheur Perfumes is a bold Eau de Parfum crafted for those who embrace confidence and effortless style. Fresh citrus notes blend seamlessly with warm spices and rich woody accords, creating a sophisticated fragrance that balances vibrant energy with lasting depth for any occasion.",
    shortDescription: 'Fresh citrus with warm spice and woody depth',
    price: 75,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    images: [{ url: '/products/img2.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Orange', 'Ginger'], middle: ['Frankincense', 'Neroli', 'Cinnamon'], base: ['Dry Amber', 'Guaiac Wood', 'Black Tea'] },
    tags: ['le bonheur', 'spicy', 'woody', 'unisex'],
  },
  {
    name: "Reine D'Or Eliza",
    slug: 'reine-dor-eliza',
    description: "Reine D'Or Eliza by Le Bonheur Perfumes is a luxurious Eau de Parfum inspired by the quiet confidence and refined presence of royalty. Delicate jasmine blossoms intertwine with the creamy richness of tuberose, creating a graceful floral composition that embodies classic femininity, sophistication, and effortless elegance.",
    shortDescription: 'Delicate jasmine and creamy tuberose',
    price: 85,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img3.png', public_id: '' }],
    notes: { top: ['Jasmine'], middle: ['Tuberose'], base: ['Floral Accords'] },
    tags: ['le bonheur', 'floral', 'women'],
  },
  {
    name: 'Black Cavalier Seductive',
    slug: 'black-cavalier-seductive',
    description: 'Black Cavalier Seductive by Le Bonheur Perfumes is a luxurious Eau de Parfum crafted for those who appreciate confidence, elegance, and timeless charm. Fresh bergamot and soothing lavender create an inviting opening, while rich patchouli, warm amber, tobacco, and black vanilla unfold into a deeply sophisticated fragrance that leaves a lasting impression.',
    shortDescription: 'Bergamot and lavender over patchouli, amber and tobacco',
    price: 75,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img4.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Lavender'], middle: ['Patchouli', 'Amber'], base: ['Vanilla', 'Tobacco'] },
    tags: ['le bonheur', 'woody', 'unisex'],
  },
  {
    name: 'Qumra Perfume',
    slug: 'qumra-perfume',
    description: 'Experience the elegance and allure of Qumra Perfume by Le Bonheur, a sophisticated fragrance crafted for the modern woman. With its captivating blend of citrus, sweet caramel, and rich vanilla, this perfume offers a luxurious scent that lingers throughout the day.',
    shortDescription: 'Citrus, sweet caramel and rich vanilla',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img5.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Cinnamon'], middle: ['Caramel'], base: ['Vanilla', 'Amber'] },
    tags: ['le bonheur', 'gourmand', 'women'],
  },
  {
    name: 'Asturi Wood',
    slug: 'asturi-wood',
    description: 'Asturi Wood by Le Bonheur Perfumes is a luxurious Eau de Parfum inspired by the beauty of golden wood glowing beneath the sunset. A delicate floral opening unfolds into a rich gourmand heart before settling into the creamy warmth of sandalwood, creating a sophisticated fragrance that embodies elegance, comfort, and lasting refinement.',
    shortDescription: 'Floral opening into creamy sandalwood',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img6.png', public_id: '' }],
    notes: { top: ['Rose'], middle: ['Caramel'], base: ['Sandalwood'] },
    tags: ['le bonheur', 'woody', 'unisex'],
  },
  {
    name: 'Remember Me Blue',
    slug: 'remember-me-blue',
    description: 'Remember Me Blue by Le Bonheur Perfumes is a modern Eau de Parfum that reflects timeless elegance and understated confidence. Blending vibrant freshness with warm, sensual depth, this masculine fragrance is designed for the man who leaves a lasting impression without saying a word.',
    shortDescription: 'Vibrant freshness with warm, sensual depth',
    price: 55,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    isBestSeller: true,
    images: [{ url: '/products/img7.png', public_id: '' }],
    notes: { top: ['Maninka Fruit', 'Apple'], middle: ['Bran', 'Patchouli', 'Cedarwood'], base: ['Sandalwood', 'Amber', 'Vanilla', 'White Musk'] },
    tags: ['le bonheur', 'fresh', 'men'],
  },
  {
    name: 'Black Cavalier VI',
    slug: 'black-cavalier-vi',
    description: 'Black Cavalier VI Perfume by Le Bonheur Perfumes is a captivating fragrance that embodies sophistication and elegance. With a masterful blend of fresh and earthy notes, this scent is perfect for anyone who seeks a bold yet refined fragrance for any occasion.',
    shortDescription: 'Fresh and earthy, bold yet refined',
    price: 75,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img8.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Ginger'], middle: ['Violet'], base: ['Cedarwood', 'Sandalwood', 'Patchouli'] },
    tags: ['le bonheur', 'earthy', 'men'],
  },
  {
    name: 'Lara',
    slug: 'lara',
    description: 'Lara by Almas Perfumes is a captivating Eau de Parfum that exudes mystery, elegance, and allure. Designed for the confident and graceful woman, this luxurious scent blends the creamy sweetness of vanilla with soft jasmine, warm sandalwood, and juicy notes of apricot and peach — creating an irresistible classic that commands attention.',
    shortDescription: 'Creamy vanilla, jasmine, sandalwood, apricot and peach',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img9.png', public_id: '' }],
    notes: { top: [], middle: ['Vanilla', 'Jasmine', 'Sandalwood'], base: ['Apricot', 'Peach'] },
    tags: ['almas', 'floral', 'women'],
  },
  {
    name: 'Moira',
    slug: 'moira',
    description: 'Immerse yourself in the luxurious scent of Moira Perfume by Almas Perfumes, a distinctive French fragrance that exudes elegance and allure. With a blend of fruity and floral notes, this captivating perfume reflects your refined personality and adds a touch of sophistication to any occasion.',
    shortDescription: 'Fruity-floral French fragrance',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img10.png', public_id: '' }],
    notes: { top: ['Cherry', 'Lychee', 'Pear'], middle: ['Rose', 'Jasmine', 'Raspberry'], base: ['Vanilla', 'Patchouli', 'Amber'] },
    tags: ['almas', 'fruity', 'women'],
  },
  {
    name: 'Aura Bloom',
    slug: 'aura-bloom',
    description: 'Let your presence linger with Aura Bloom by Almas Perfumes, a French-style Eau de Parfum that tells your story with every note. Rich, elegant, and irresistibly feminine, this fragrance opens with a burst of sweet fruitiness, flows into a radiant floral-amber heart, and finishes with a warm, creamy base. Designed for women who embody sophistication and unforgettable grace.',
    shortDescription: 'Sweet fruitiness into a floral-amber heart',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img11.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Plum', 'Red Fruits'], middle: ['Amber', 'Jasmine'], base: ['Caramel Cream', 'Musk', 'Vanilla'] },
    tags: ['almas', 'fruity', 'women'],
  },
  {
    name: 'Wow Pistachio',
    slug: 'wow-pistachio',
    description: 'Elevate your scent game with Wow Pistachio by Almas Perfumes, a unisex Eau de Parfum that exudes luxury and warmth. This decadent fragrance blends creamy pistachio with sweet vanilla and soft woody notes, delivering a bold yet comforting aroma that lingers beautifully. Designed for fragrance lovers who seek uniqueness and elegance in every spray.',
    shortDescription: 'Creamy pistachio with sweet vanilla and soft wood',
    price: 85,
    comparePrice: 0,
    gender: 'Unisex',
    size: '200ml',
    stock: 30,
    isFeatured: true,
    isBestSeller: true,
    images: [{ url: '/products/img12.png', public_id: '' }],
    notes: { top: ['Pistachio', 'Almond', 'Bergamot'], middle: ['Jasmine', 'Caramel', 'White Flowers'], base: ['Vanilla', 'Tonka Bean', 'Sandalwood'] },
    tags: ['almas', 'gourmand', 'unisex'],
  },
  {
    name: 'White Heart',
    slug: 'white-heart',
    description: 'Experience the brilliance and distinction of White Heart, a captivating fragrance by Almas Perfumes. This vibrant perfume blends citrus, fruity, and warm notes to create a refreshing and luxurious scent. Perfect for both personal and formal occasions, White Heart makes you feel lively and wonderful throughout the day.',
    shortDescription: 'Citrus, fruity and warm musk-amber notes',
    price: 55,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img13.png', public_id: '' }],
    notes: { top: ['Orange', 'Bergamot', 'Lemon'], middle: ['Fruits'], base: ['White Musk', 'Amber', 'Madagascar Vanilla'] },
    tags: ['almas', 'citrus', 'unisex'],
  },
  {
    name: 'Everyday Sweety',
    slug: 'everyday-sweety',
    description: 'Everyday Sweety Perfume by Almas Perfumes offers a captivating and luxurious fragrance designed for women who appreciate elegance and charm. This exquisite French perfume, with its unique blend of honey, bergamot, and cashmere, adds a touch of brilliance to your daily look, leaving a lasting impression with its long-lasting scent.',
    shortDescription: 'Honey, bergamot and cashmere',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img14.png', public_id: '' }],
    notes: { top: ['Honey', 'Bergamot', 'Orange'], middle: ['Cashmere', 'Apple', 'Caramel'], base: ['Musk', 'Vanilla', 'Patchouli'] },
    tags: ['almas', 'gourmand', 'women'],
  },
  {
    name: 'Club de Nuit Intense Man',
    slug: 'club-de-nuit-intense-man',
    description: 'Club de Nuit Intense Man by Armaf is a Woody Spicy fragrance for men, launched in 2015.',
    shortDescription: 'Woody spicy fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img15.png', public_id: '' }],
    notes: { top: ['Lemon', 'Pineapple', 'Bergamot', 'Black Currant', 'Apple'], middle: ['Birch', 'Jasmine', 'Rose'], base: ['Musk', 'Ambergris', 'Patchouli', 'Vanilla'] },
    tags: ['armaf', 'woody', 'spicy', 'men'],
  },
  {
    name: 'Club de Nuit Untold',
    slug: 'club-de-nuit-untold',
    description: 'Club de Nuit Untold by Armaf is a fragrance for women and men, launched in 2022.',
    shortDescription: 'Saffron and jasmine over amberwood and cedar',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img16.png', public_id: '' }],
    notes: { top: ['Saffron', 'Jasmine'], middle: ['Amberwood', 'Ambergris'], base: ['Fir Resin', 'Cedar'] },
    tags: ['armaf', 'unisex'],
  },
  {
    name: 'Club De Nuit Maleka',
    slug: 'club-de-nuit-maleka',
    description: 'Club De Nuit Maleka by Armaf is a Floral Fruity fragrance for women, launched in 2025. The nose behind this fragrance is Olivier Cresp.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img17.png', public_id: '' }],
    notes: { top: ['Lychee', 'Bergamot', 'Pink Pepper'], middle: ['Orris'], base: ['Praline', 'Sandalwood', 'Ambroxan'] },
    tags: ['armaf', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Musamam White Intense',
    slug: 'musamam-white-intense',
    description: 'Musamam White Intense by Lattafa Perfumes is an Oriental Floral fragrance for women and men, launched in 2023. The nose behind this fragrance is Gaël Montero.',
    shortDescription: 'Oriental floral fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img18.png', public_id: '' }],
    notes: { top: ['Spices', 'Bergamot', 'Orange'], middle: ['Coconut', 'Ylang Ylang', 'Ambroxan', 'Mahonial'], base: ['Sandalwood', 'Musk', 'Benzoin'] },
    tags: ['lattafa', 'oriental', 'floral', 'unisex'],
  },
  {
    name: 'Angham',
    slug: 'angham',
    description: 'Angham by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2024.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img19.png', public_id: '' }],
    notes: { top: ['Ginger', 'Mandarin', 'Pink Pepper'], middle: ['Lavender', 'Praline', 'Cacao', 'Jasmine'], base: ['Vanilla', 'Amber', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: "Bade'e Al Oud Sublime",
    slug: 'badee-al-oud-sublime',
    description: "Bade'e Al Oud Sublime by Lattafa Perfumes is a Woody Aromatic fragrance for women and men, launched in 2023.",
    shortDescription: 'Woody aromatic fragrance for women and men',
    price: 50,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img20.png', public_id: '' }],
    notes: { top: ['Apple', 'Litchi', 'Rose'], middle: ['Plum', 'Jasmine'], base: ['Moss', 'Vanilla', 'Patchouli'] },
    tags: ['lattafa', 'woody', 'unisex'],
  },
  {
    name: 'Cloud Candy',
    slug: 'cloud-candy',
    description: 'Cloud Candy by Khadlaj Perfumes is a fragrance for women and men, launched in 2025.',
    shortDescription: 'Sweet gourmand fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img21.png', public_id: '' }],
    notes: { top: [], middle: ['Marshmallow', 'Strawberry', 'Sugar', 'Whipped Cream', 'Vanilla', 'Raspberry', 'White Musk', 'Coconut', 'Tangerine', 'Ambroxan', 'Freesia'], base: [] },
    tags: ['khadlaj', 'gourmand', 'women'],
  },
  {
    name: 'Vintage Radio',
    slug: 'vintage-radio',
    description: 'Vintage Radio by Lattafa Perfumes is an Oriental Woody fragrance for women and men, launched in 2023.',
    shortDescription: 'Oriental woody fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img22.png', public_id: '' }],
    notes: { top: ['Lavender', 'Sage', 'Bergamot'], middle: ['Plum', 'Palo Santo', 'Black Pepper'], base: ['Sandalwood', 'Oud'] },
    tags: ['lattafa', 'oriental', 'woody', 'unisex'],
  },
  {
    name: 'Victoria',
    slug: 'victoria',
    description: 'Victoria by Lattafa Perfumes is a Floral Fruity Gourmand fragrance for women and men, launched in 2025.',
    shortDescription: 'Floral fruity gourmand fragrance',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img23.png', public_id: '' }],
    notes: { top: ['Lemon Meringue Pie'], middle: ['Neroli'], base: ['Vanilla'] },
    tags: ['lattafa', 'gourmand', 'unisex'],
  },
  {
    name: 'Fatima Pink',
    slug: 'fatima-pink',
    description: 'Fatima Pink by Zimaya is an Oriental Floral fragrance for women, launched in 2023.',
    shortDescription: 'Oriental floral fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img24.png', public_id: '' }],
    notes: { top: ['Rhubarb', 'Bergamot', 'Grapefruit', 'Nutmeg'], middle: ['Rose', 'Jasmine'], base: ['Musk', 'Vanilla', 'Vetiver', 'Ambergris'] },
    tags: ['zimaya', 'oriental', 'floral', 'women'],
  },
  {
    name: 'Opulent Dubai',
    slug: 'opulent-dubai',
    description: 'Opulent Dubai by Lattafa Perfumes is an Oriental Floral fragrance for women and men, launched in 2025.',
    shortDescription: 'Oriental floral fragrance for women and men',
    price: 60,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img25.png', public_id: '' }],
    notes: { top: ['Mango', 'Grapefruit', 'Lemon', 'Ginger'], middle: ['Jasmine', 'Cedarwood', 'Violet'], base: ['Woodsy Notes', 'Ambergris', 'Oakmoss', 'Benzoin'] },
    tags: ['lattafa', 'oriental', 'unisex'],
  },
  {
    name: 'Atheeri',
    slug: 'atheeri',
    description: 'Atheeri by Lattafa Perfumes is an Oriental Floral fragrance for women, launched in 2025.',
    shortDescription: 'Oriental floral fragrance for women',
    price: 70,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img26.png', public_id: '' }],
    notes: { top: ['Passion Flower', 'Dew Drop'], middle: ['Orchid', 'Jasmine'], base: ['Vanilla', 'Amberwood'] },
    tags: ['lattafa', 'oriental', 'floral', 'women'],
  },
  {
    name: 'Nebras',
    slug: 'nebras',
    description: 'Nebras by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2022.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img27.png', public_id: '' }],
    notes: { top: ['Red Berries', 'Mandarin Orange'], middle: ['Vanilla', 'Cacao', 'Rose'], base: ['Sugar', 'Tonka Bean', 'Amber', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: 'Nebras Elixir',
    slug: 'nebras-elixir',
    description: 'Nebras Elixir by Lattafa Perfumes is an Oriental Vanilla fragrance for women and men, launched in 2025. The nose behind this fragrance is Nanako Ogi.',
    shortDescription: 'Oriental vanilla fragrance for women and men',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img28.png', public_id: '' }],
    notes: { top: ['Milk Candy', 'Whipped Cream'], middle: ['Sugar Cane', 'Heliotrope'], base: ['Vanilla', 'Ambroxan', 'Musk'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'unisex'],
  },
  {
    name: 'Pacific',
    slug: 'pacific',
    description: 'Pacific by Rayhaan is a fragrance for men, launched in 2022.',
    shortDescription: 'Fresh aromatic fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img29.png', public_id: '' }],
    notes: { top: ['Bergamot', 'Lemon', 'Tangerine', 'Cardamom'], middle: ['Lavender', 'Cypress'], base: ['Amber'] },
    tags: ['rayhaan', 'fresh', 'men'],
  },
  {
    name: 'Ameerat Al Arab',
    slug: 'ameerat-al-arab',
    description: 'Ameerat Al Arab (Princess of Arabia) by Asdaaf is a Floral fragrance for women, launched in 2022.',
    shortDescription: 'Floral fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img30.png', public_id: '' }],
    notes: { top: ['Citruses', 'Bergamot'], middle: ['White Musk', 'Aloe Vera'], base: ['Jasmine', 'Musk', 'Woody Notes', 'Oud'] },
    tags: ['asdaaf', 'floral', 'women'],
  },
  {
    name: 'Ameerat Al Arab Prive Rose',
    slug: 'ameerat-al-arab-prive-rose',
    description: 'Ameerat Al Arab Prive Rose (Princess of Arabia Pink) by Asdaaf is a Floral Fruity fragrance for women, launched in 2023.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img31.png', public_id: '' }],
    notes: { top: ['Strawberry', 'Grapes', 'Orange'], middle: ['Rose', 'White Musk', 'Jasmine', 'Gardenia', 'Ylang-Ylang', 'Lily'], base: ['Tonka Bean', 'Amber', 'Sandalwood'] },
    tags: ['asdaaf', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Peace & Love',
    slug: 'peace-and-love',
    description: 'Peace & Love by Lattafa Perfumes is a Floral fragrance for women and men, launched in 2024.',
    shortDescription: 'Floral fragrance for women and men',
    price: 80,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img32.png', public_id: '' }],
    notes: { top: ['Almond', 'Black Currant', 'Bergamot'], middle: ['Rose', 'Tuberose'], base: ['Sandalwood', 'Vanilla', 'Heliotrope'] },
    tags: ['lattafa', 'floral', 'unisex'],
  },
  {
    name: 'Amber Oud Bleu Edition',
    slug: 'amber-oud-bleu-edition',
    description: 'Amber Oud Bleu Edition by Al Haramain Perfumes is a fragrance for women and men, launched in 2022.',
    shortDescription: 'Fresh citrus over woody amber',
    price: 100,
    comparePrice: 0,
    gender: 'Unisex',
    size: '60ml',
    stock: 30,
    isFeatured: true,
    images: [{ url: '/products/img33.png', public_id: '' }],
    notes: { top: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'], middle: ['Ginger', 'Vetiver', 'Jasmine'], base: ['Olibanum', 'Sandalwood', 'Cedar', 'Patchouli'] },
    tags: ['al haramain', 'woody', 'unisex'],
  },
  {
    name: 'Delilah pour femme',
    slug: 'delilah-pour-femme',
    description: 'Delilah by Maison Alhambra is a Floral Fruity fragrance for women, launched in 2023.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img34.png', public_id: '' }],
    notes: { top: ['Rhubarb', 'Litchi', 'Bergamot'], middle: ['Turkish Rose', 'Peony', 'Lily'], base: ['White Musk', 'Cashmeran', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Delilah Blanc',
    slug: 'delilah-blanc',
    description: 'Delilah Blanc by Maison Alhambra is a Floral Fruity fragrance for women, launched in 2024.',
    shortDescription: 'Floral fruity fragrance for women',
    price: 60,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img35.png', public_id: '' }],
    notes: { top: ['Bergamot', 'White Peach', 'Mandarin'], middle: ['Orange Blossom', 'Vetiver'], base: ['Musk', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'women'],
  },
  {
    name: 'Delilah Viola',
    slug: 'delilah-viola',
    description: 'Delilah Viola by Maison Alhambra is a Floral Fruity fragrance for women and men, launched in 2026.',
    shortDescription: 'Floral fruity fragrance for women and men',
    price: 70,
    comparePrice: 0,
    gender: 'Unisex',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img36.png', public_id: '' }],
    notes: { top: ['Pear', 'Mandarin Orange', 'Bergamot', 'Peach'], middle: ['Lilac', 'Violet', 'Lily of the Valley', 'Lavender'], base: ['White Musk', 'Cream', 'Sandalwood', 'Patchouli', 'Vanilla'] },
    tags: ['maison alhambra', 'floral', 'fruity', 'unisex'],
  },
  {
    name: 'Liquid Brun',
    slug: 'liquid-brun',
    description: 'Liquid Brun by French Avenue is a Woody fragrance for men, launched in 2024.',
    shortDescription: 'Woody fragrance for men',
    price: 80,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img37.png', public_id: '' }],
    notes: { top: ['Cinnamon', 'Orange Blossom', 'Cardamom', 'Bergamot'], middle: ['Bourbon Vanilla', 'Elemi'], base: ['Praline', 'Ambroxan', 'Musk', 'Guaiac Wood'] },
    tags: ['french avenue', 'woody', 'men'],
  },
  {
    name: 'Asad Zanzibar Limited Edition',
    slug: 'asad-zanzibar-limited-edition',
    description: 'Asad Zanzibar Limited Edition by Lattafa Perfumes is an Oriental Spicy fragrance for men, launched in 2025.',
    shortDescription: 'Oriental spicy fragrance for men',
    price: 60,
    comparePrice: 0,
    gender: 'For Him',
    size: '100ml',
    stock: 30,
    isNewArrival: true,
    images: [{ url: '/products/img38.png', public_id: '' }],
    notes: { top: ['Marine Notes', 'Lavender', 'Pink Pepper'], middle: ['Soap', 'Cashmeran', 'Cinnamon'], base: ['Amber', 'Sandalwood', 'Tonka Bean', 'Cedar'] },
    tags: ['lattafa', 'oriental', 'spicy', 'men'],
  },
  {
    name: 'Yara',
    slug: 'yara',
    description: 'Yara by Lattafa Perfumes is an Oriental Vanilla fragrance for women, launched in 2020.',
    shortDescription: 'Oriental vanilla fragrance for women',
    price: 50,
    comparePrice: 0,
    gender: 'For Her',
    size: '100ml',
    stock: 30,
    images: [{ url: '/products/img39.png', public_id: '' }],
    notes: { top: ['Orchid', 'Heliotrope', 'Tangerine'], middle: ['Gourmand Accord', 'Tropical Fruits'], base: ['Vanilla', 'Musk', 'Sandalwood'] },
    tags: ['lattafa', 'oriental', 'vanilla', 'women'],
  },
];

const seed = async () => {
  try {
    await connectDB();

    // 1. Admin user
    const adminEmail = process.env.SEED_ADMIN_EMAIL || 'admin@fusionscent.com';
    const adminPassword = process.env.SEED_ADMIN_PASSWORD || 'Admin@12345';

    let admin = await User.findOne({ email: adminEmail });
    if (!admin) {
      admin = await User.create({
        name: 'FusionScent Admin',
        email: adminEmail,
        password: adminPassword,
        role: 'admin',
      });
      console.log(`Admin created -> email: ${adminEmail} | password: ${adminPassword}`);
    } else {
      console.log(`Admin already exists -> ${adminEmail}`);
    }

    // 2. Categories
    const categoryMap = {};
    for (const cat of categoriesData) {
      let existing = await Category.findOne({ slug: cat.slug });
      if (!existing) {
        existing = await Category.create(cat);
        console.log(`Category created: ${cat.name}`);
      }
      categoryMap[cat.name] = existing._id;
    }

    // 3. Remove old placeholder products
    const removed = await Product.deleteMany({ slug: { $in: legacySlugs } });
    if (removed.deletedCount) console.log(`Removed ${removed.deletedCount} legacy placeholder product(s)`);

    // 4. Products
    for (const prod of productsData) {
      const existing = await Product.findOne({ slug: prod.slug });
      if (existing) {
        console.log(`Product already exists: ${prod.name}`);
        continue;
      }
      const categoryId = categoryMap[prod.gender] || categoryMap['Unisex'];
      await Product.create({ ...prod, category: categoryId });
      console.log(`Product created: ${prod.name}`);
    }

    console.log('Seeding complete.');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seed();
